name: Deploy ML Model

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: starlit-byway-436420-s9

    - name: Build Docker image
      run: docker build -t gcr.io/starlit-byway-436420-s9/ner-bert:latest 

    - name: Push to Google Container Registry
      run: docker push gcr.io/starlit-byway-436420-s9/ner-bert:latest 